baseURL = "https://www.redradrat.xyz/"
languageCode = "en-us"
theme = "hugo-coder"
title = "redradrat"
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
[[menu.main]]
name = "Contact me"
url = "/contact/"
weight = 5
[params]
author = "Ralph KÃ¼hnert"
avatarurl = "images/redradrat-round.png"
description = "Love sheep, be unique. Personal blog and projects."
footercontent = "Love sheep, be unique."
hideCopyright = false
hideCredits = true
info = "DevOps Dude, Cloud Architect and Weathermaker"
keywords = "blog,developer,personal"
[[params.social]]
name = "GitHub"
url = "https://github.com/redradrat/"
weight = 1
